import type { Ilan, Not } from './types'

// Türkiye il listesi (filtreleme ve form için)
export const ILLER = [
  'Adana',
  'Adıyaman',
  'Afyonkarahisar',
  'Ağrı',
  'Aksaray',
  'Amasya',
  'Ankara',
  'Antalya',
  'Ardahan',
  'Artvin',
  'Aydın',
  'Balıkesir',
  'Bartın',
  'Batman',
  'Bayburt',
  'Bilecik',
  'Bingöl',
  'Bitlis',
  'Bolu',
  'Burdur',
  'Bursa',
  'Çanakkale',
  'Çankırı',
  'Çorum',
  'Denizli',
  'Diyarbakır',
  'Düzce',
  'Edirne',
  'Elazığ',
  'Erzincan',
  'Erzurum',
  'Eskişehir',
  'Gaziantep',
  'Giresun',
  'Gümüşhane',
  'Hakkari',
  'Hatay',
  'Iğdır',
  'Isparta',
  'İstanbul',
  'İzmir',
  'Kahramanmaraş',
  'Karabük',
  'Karaman',
  'Kars',
  'Kastamonu',
  'Kayseri',
  'Kırıkkale',
  'Kırklareli',
  'Kırşehir',
  'Kilis',
  'Kocaeli',
  'Konya',
  'Kütahya',
  'Malatya',
  'Manisa',
  'Mardin',
  'Mersin',
  'Muğla',
  'Muş',
  'Nevşehir',
  'Niğde',
  'Ordu',
  'Osmaniye',
  'Rize',
  'Sakarya',
  'Samsun',
  'Siirt',
  'Sinop',
  'Sivas',
  'Şanlıurfa',
  'Şırnak',
  'Tekirdağ',
  'Tokat',
  'Trabzon',
  'Tunceli',
  'Uşak',
  'Van',
  'Yalova',
  'Yozgat',
  'Zonguldak',
]

export const YUK_CINSLERI = [
  'Paletli',
  'Dökme',
  'Çuval',
  'Tenteli',
  'Frigo',
  'Konteyner',
  'Kırkayak / Lowbed',
  'Diğer',
] as const

function daysAgo(n: number, hours = 0): string {
  const d = new Date()
  d.setDate(d.getDate() - n)
  d.setHours(d.getHours() - hours)
  return d.toISOString()
}

export const SEED_ILANLAR: Ilan[] = [
  {
    id: 'i1',
    tur: 'yuk',
    kalkis_il: 'İstanbul',
    kalkis_ilce: 'Hadımköy',
    varis_il: 'Ankara',
    varis_ilce: 'Sincan',
    yuk_cinsi: 'Paletli',
    tonaj: 24,
    hacim: 86,
    fiyat: 18500,
    aciklama: 'Gıda ürünü, paletli yükleme. Tenteli tır aranıyor, forkliftle yükleme yapılacak.',
    ilan_sahibi: 'Mehmet Lojistik',
    telefon: '5321234567',
    ilan_tarihi: daysAgo(0, 2),
  },
  {
    id: 'i2',
    tur: 'yuk',
    kalkis_il: 'İzmir',
    kalkis_ilce: 'Kemalpaşa',
    varis_il: 'Bursa',
    varis_ilce: 'İnegöl',
    yuk_cinsi: 'Dökme',
    tonaj: 27,
    fiyat: 9800,
    aciklama: 'Dökme hububat yükü. Damperli veya silobas uygundur. Aynı gün yükleme.',
    ilan_sahibi: 'Ege Tarım',
    telefon: '5442345678',
    ilan_tarihi: daysAgo(0, 6),
  },
  {
    id: 'i3',
    tur: 'arac',
    kalkis_il: 'Konya',
    kalkis_ilce: 'Merkez',
    varis_il: 'İstanbul',
    varis_ilce: 'Tümü',
    yuk_cinsi: 'Tenteli',
    tonaj: 26,
    fiyat: 0,
    aciklama: 'Boş tenteli tır, Konya çıkışlı İstanbul yönüne yük arıyor. Yarın sabah müsait.',
    ilan_sahibi: 'Ahmet Şoför',
    telefon: '5053456789',
    ilan_tarihi: daysAgo(1),
  },
  {
    id: 'i4',
    tur: 'yuk',
    kalkis_il: 'Gaziantep',
    kalkis_ilce: 'Başpınar OSB',
    varis_il: 'Mersin',
    varis_ilce: 'Liman',
    yuk_cinsi: 'Konteyner',
    tonaj: 22,
    fiyat: 7200,
    aciklama: '40 HC konteyner limana götürülecek. Boş dönüş yük ayarlanabilir.',
    ilan_sahibi: 'Antep Nakliyat',
    telefon: '5364567890',
    ilan_tarihi: daysAgo(1, 4),
  },
  {
    id: 'i5',
    tur: 'yuk',
    kalkis_il: 'Antalya',
    kalkis_ilce: 'Kumluca',
    varis_il: 'İstanbul',
    varis_ilce: 'Hal',
    yuk_cinsi: 'Frigo',
    tonaj: 20,
    fiyat: 22000,
    aciklama: 'Sebze-meyve yükü, frigolu araç şart. -2 derece. Gece yükleme.',
    ilan_sahibi: 'Akdeniz Sebze',
    telefon: '5475678901',
    ilan_tarihi: daysAgo(2),
  },
  {
    id: 'i6',
    tur: 'yuk',
    kalkis_il: 'Kocaeli',
    kalkis_ilce: 'Gebze',
    varis_il: 'Kayseri',
    varis_ilce: 'OSB',
    yuk_cinsi: 'Çuval',
    tonaj: 25,
    fiyat: 15400,
    aciklama: 'Çuvallı kimyasal hammadde. Kapalı kasa/tenteli. Yükleme rampadan.',
    ilan_sahibi: 'Marmara Kimya',
    telefon: '5386789012',
    ilan_tarihi: daysAgo(2, 5),
  },
  {
    id: 'i7',
    tur: 'arac',
    kalkis_il: 'Samsun',
    kalkis_ilce: 'Tekkeköy',
    varis_il: 'Ankara',
    varis_ilce: 'Tümü',
    yuk_cinsi: 'Frigo',
    tonaj: 18,
    fiyat: 0,
    aciklama: 'Boş frigo kamyon, Samsun-Ankara arası dönüş yükü arıyor.',
    ilan_sahibi: 'Karadeniz Soğuk Zincir',
    telefon: '5397890123',
    ilan_tarihi: daysAgo(3),
  },
  {
    id: 'i8',
    tur: 'yuk',
    kalkis_il: 'Denizli',
    kalkis_ilce: 'Merkezefendi',
    varis_il: 'İzmir',
    varis_ilce: 'Aliağa',
    yuk_cinsi: 'Kırkayak / Lowbed',
    tonaj: 40,
    fiyat: 28000,
    aciklama: 'İş makinesi taşınacak, lowbed gerekli. Genişlik izni alıcıya ait.',
    ilan_sahibi: 'Ege İş Makineleri',
    telefon: '5308901234',
    ilan_tarihi: daysAgo(3, 8),
  },
]

export const SEED_NOTLAR: Not[] = [
  {
    id: 'n1',
    baslik: 'Ön lastik değişimi',
    icerik: 'Ön lastikler 285.000 km değişecek. Michelin X-Multi bakılacak.',
    kategori: 'lastik',
    hatirlatma_km: 285000,
    olusturma_tarihi: daysAgo(5),
  },
  {
    id: 'n2',
    baslik: 'Araç muayenesi',
    icerik: 'TÜVTÜRK randevusu alınacak, egzoz emisyon dahil.',
    kategori: 'muayene',
    hatirlatma_tarihi: '2026-09-15',
    olusturma_tarihi: daysAgo(8),
  },
  {
    id: 'n3',
    baslik: 'Kasko yenileme',
    icerik: 'Kasko poliçesi bitmeden acenteyi ara, indirimli teklif iste.',
    kategori: 'sigorta',
    hatirlatma_tarihi: '2026-08-30',
    olusturma_tarihi: daysAgo(10),
  },
]
